const MODELS = [
  {
    id: "gpt-5.5",
    vendor: "openai",
    name: "GPT-5.5",
    input: 5.0,
    output: 30.0,
    cacheWrite: 5.0,
    cacheRead: 0.5,
  },
  {
    id: "gpt-5.5-pro",
    vendor: "openai",
    name: "GPT-5.5-pro",
    input: 30,
    output: 180,
    cacheWrite: 0,
    cacheRead: 0,
  },
  {
    id: "gpt-5.4",
    vendor: "openai",
    name: "GPT-5.4",
    input: 2.5,
    output: 15.0,
    cacheWrite: 2.5,
    cacheRead: 0.25,
  },
  {
    id: "gpt-5.4-mini",
    vendor: "openai",
    name: "GPT-5.4 Mini",
    input: 0.75,
    output: 4.5,
    cacheWrite: 0.75,
    cacheRead: 0.075,
  },
  {
    id: "gpt-5.4-nano",
    vendor: "openai",
    name: "GPT-5.4 Nano",
    input: 0.2,
    output: 1.25,
    cacheWrite: 0.2,
    cacheRead: 0.02,
  },
  {
    id: "gpt-5.4-pro",
    vendor: "openai",
    name: "GPT-5.4 Pro",
    input: 21.0,
    output: 168.0,
    cacheWrite: 0,
    cacheRead: 0,
  },
  {
    id: "claude-opus-4.7",
    vendor: "anthropic",
    name: "Claude Opus 4.7",
    input: 5.0,
    output: 25.0,
    cacheWrite: 6.25,
    cacheRead: 0.5,
  },
  {
    id: "claude-opus-4.6",
    vendor: "anthropic",
    name: "Claude Opus 4.6",
    input: 5.0,
    output: 25.0,
    cacheWrite: 6.25,
    cacheRead: 0.5,
  },
  {
    id: "claude-sonnet-4.6",
    vendor: "anthropic",
    name: "Claude Sonnet 4.6",
    input: 3.0,
    output: 15.0,
    cacheWrite: 3.75,
    cacheRead: 0.3,
  },
  {
    id: "claude-haiku-4.5",
    vendor: "anthropic",
    name: "Claude Haiku 4.5",
    input: 1.0,
    output: 5.0,
    cacheWrite: 1.25,
    cacheRead: 0.1,
  },
  {
    id: "claude-opus-4.5",
    vendor: "anthropic",
    name: "Claude Opus 4.5",
    input: 5.0,
    output: 25.0,
    cacheWrite: 6.25,
    cacheRead: 0.5,
  },
  {
    id: "claude-sonnet-4.5",
    vendor: "anthropic",
    name: "Claude Sonnet 4.5",
    input: 3.0,
    output: 15.0,
    cacheWrite: 3.75,
    cacheRead: 0.3,
  },
  {
    id: "gemini-3.1-pro",
    vendor: "google",
    name: "Gemini 3.1 Pro",
    input: 2.0,
    output: 12.0,
    cacheWrite: 2.0,
    cacheRead: 0.5,
  },
  {
    id: "gemini-3-flash",
    vendor: "google",
    name: "Gemini 3 Flash",
    input: 0.5,
    output: 3.0,
    cacheWrite: 0.5,
    cacheRead: 0.05,
  },
  {
    id: "gemini-3-deep-think",
    vendor: "google",
    name: "Gemini 3 Deep Think",
    input: 4.0,
    output: 24.0,
    cacheWrite: 4.0,
    cacheRead: 1.0,
  },
  {
    id: "gemini-2.5-pro",
    vendor: "google",
    name: "Gemini 2.5 Pro",
    input: 1.25,
    output: 10.0,
    cacheWrite: 1.25,
    cacheRead: 0.125,
  },
  {
    id: "gemini-2.5-flash",
    vendor: "google",
    name: "Gemini 2.5 Flash",
    input: 0.3,
    output: 2.5,
    cacheWrite: 0.3,
    cacheRead: 0.03,
  },
  {
    id: "gemini-2.5-flash-lite",
    vendor: "google",
    name: "Gemini 2.5 Flash-Lite",
    input: 0.1,
    output: 0.4,
    cacheWrite: 0.1,
    cacheRead: 0.01,
  },
  {
    id: "deepseek-v4",
    vendor: "deepseek",
    name: "DeepSeek V4 Flash",
    input: 0.14,
    output: 0.28,
    cacheWrite: 0.14,
    cacheRead: 0.0028,
  },
  {
    id: "deepseek-v4-pro",
    vendor: "deepseek",
    name: "DeepSeek V4 Pro*",
    input: 0.435,
    output: 0.87,
    cacheWrite: 0.435,
    cacheRead: 0.003625,
  },
];

const VENDORS = ["openai", "anthropic", "google", "deepseek"];
